Zac-HD/hypofuzz

src/hypofuzz/hy.py
arg name `etype` has changed in Python 3.10, use positional arg instead.
Closes #16
=> fixing arg name etype in format_exception

CONTRIBUTING.md, src/hypofuzz/hy.py
Noticed in passing; untested.
I've added myself to the authors list not because I think the fix is deserving of it (it's not!), but because you seem relatively serious about the licensing CLA, and I want to respect that.
A sidenote: this repository seems to be using CRLF for line endings — a fact I discovered when git helpfully autoconverted them to LF for me on commit, resulting in an unreadable github diff. It might be nice to do a one-time pass to LF on all files.
=> Fix missing f-string

src/hypofuzz/entrypoint.py
The reason for this PR is that I am often running the hypofuzz server in my homelab now and in order to access the dashboard from my workstation, I always need to apply this patch after installation :see_no_evil: Would it be acceptable to actually incorporate this as a cli argument? I intentionally kept the changes minimal, without adding IPv4/IPv6/FQDN validation, but if you find it useful, I can also add a custom `click` type instead of the plain `str`.
```diff
@@ -344,7 +344,7 @@ def patch_summary() -> flask.Response:
def start_dashboard_process(
-    port: int, *, pytest_args: list, host: str = "localhost", debug: bool = False
+    port: int, *, pytest_args: list, host: str = "0.0.0.0", debug: bool = False
) -> None:
global PYTEST_ARGS
PYTEST_ARGS = pytest_args
```
=> Allow passing host when starting the dashboard

docs-src/changelog.md, src/hypofuzz/__init__.py, src/hypofuzz/dashboard.py, src/hypofuzz/entrypoint.py, tests/common.py, tests/test_dashboard.py, tests/test_e2e.py
Contains a very rough start on a dashboard api - just enough to write a few basic tests.
=> Respect database in dashboard (and add tests)

deps/check.txt, deps/docs.txt, deps/test-old.txt, deps/test.txt, docs-src/changelog.md, setup.py, src/hypofuzz/__init__.py, src/hypofuzz/cov.py, src/hypofuzz/database.py, src/hypofuzz/hy.py, tests/common.py, tests/test_dashboard.py, tests/test_database.py, tox.ini
For the database, it's mostly `seed_pool` which can be very large, and we only need that attribute for the latest entry. (now that I write this,  we may want to stick attrs like this into a separate key `.metadata-latest` instead so we don't have to do the reduce-old-reports song and dance).
I'd like to write lots of tests for coverage - eventually. Needs its own entire pull. But if you see a missing cov instrumention test which blocks this pull, let me know.
=> Use `sys.monitoring` and optimize db usage

docs-src/changelog.md, src/hypofuzz/__init__.py, src/hypofuzz/interface.py, tests/test_collection.py
This happens when fuzzing Hypothesis itself, as our `_consistently_increment_time` autouse fixture uses the `monkeypatch` fixture. See also https://github.com/Zac-HD/hypofuzz/issues/38#issuecomment-2188172857.
=> Support autouse fixtures that request another fixture

docs-src/changelog.md, setup.py, src/hypofuzz/__init__.py, src/hypofuzz/corpus.py, src/hypofuzz/hy.py, src/hypofuzz/interface.py, tests/test_collection.py
Parametrized node ids Just Work ™️ in the dashboard....as long as you aren't doing anything too cursed, like duplicating names. Skipif is evaluated and skipped during collection, including support for condition strings.
I haven't tested this with more complicated things like classes or ~~module-level skips~~ (added tests for the latter). 
Also tacked on to this pull: update our database usage from buffer to choices.
=> Initial support for parameterization and skipif

docs-src/changelog.md, setup.py, src/hypofuzz/__init__.py
We removed the buffer in `6.124.4` - whoops! I'll work on supporting this as my next task but may not be able to get to it until the weekend.
=> Pin hypothesis to 6.124.3

deps/check.in, deps/check.txt, deps/docs.txt, deps/test-old.txt, deps/test.txt, docs-src/changelog.md, setup.py, src/hypofuzz/__init__.py, src/hypofuzz/corpus.py, src/hypofuzz/cov.py, src/hypofuzz/database.py, src/hypofuzz/debugger.py, src/hypofuzz/hy.py, src/hypofuzz/interface.py, src/hypofuzz/provider.py, tests/common.py, tests/strategies.py, tests/test_corpus.py, tests/test_provider.py
Ditches the buffer mutator in favor of an (extremely simple) tcs mutator.
TBH I have relatively low confidence that the logic in `corpus.py` is correct after this change. I see more test writing in my future...
=> Move to a typed choice sequence mutator

docs-src/changelog.md, src/hypofuzz/__init__.py, src/hypofuzz/interface.py, tests/test_collection.py
Closes #38. Depends on #50 for a clean merge.
This requires a small amount of refactoring Hypothesis-side, including setting a new `runTest._hypothesis_state_machine_class = cls` attribute. I don't have a *great* grasp of the stateful testing internals, so I may be overcomplicating things? It seems that what Hypofuzz really wants to access is the underlying `@given` which drives stateful test - and to get to that we need to rejig some code.
Here's the Hypothesis-side companion diff, which I can PR to Hypothesis:
```diff
diff --git a/hypothesis-python/src/hypothesis/stateful.py b/hypothesis-python/src/hypothesis/stateful.py
index f1dfa5205..ae8ccd36c 100644
--- a/hypothesis-python/src/hypothesis/stateful.py
+++ b/hypothesis-python/src/hypothesis/stateful.py
@@ -83,14 +83,7 @@ class …
```
=> Initial support for stateful testing

pyproject.toml
Latest CI attempt *built*, but with a version of 0.0.0, and so skipped the pypi upload. Apparently for the `setuptools` backend any dynamic attribute needs a matching [tool.setuptools.dynamic] key.
=> Set version when building

docs-src/changelog.md, src/hypofuzz/__init__.py, src/hypofuzz/frontend/src/components/CoverageGraph.tsx, src/hypofuzz/frontend/src/components/Table.tsx, src/hypofuzz/frontend/src/components/TestTable.tsx, src/hypofuzz/frontend/src/pages/CollectionStatus.tsx, src/hypofuzz/frontend/src/styles.scss
Also remove the right-side list of all tests in the graph, which is probably better served by the ability to search for tests? Node ids are usually too long for listing them on the sidebar to be reasonable ui.
=> Improve mobile table ui

src/hypofuzz/interface.py, tests/test_collection.py
I expect fuzzing (strict-)xfail tests to be pretty low-value, so I'm pretty happy to just skip them for the foreseeable future.
=> Skip collecting xfail tests

build.sh, src/hypofuzz/dashboard/dashboard.py, src/hypofuzz/dashboard/models.py, src/hypofuzz/dashboard/test.py, src/hypofuzz/database.py, src/hypofuzz/frontend/src/context/DataProvider.tsx, src/hypofuzz/hypofuzz.py, src/hypofuzz/interface.py, tests/common.py, tests/test_dashboard.py, tests/test_database.py
I'm pretty happy with this, except again the note that the listener knows that a failure (observation) has been deleted, but not *which* failure. We don't expect there to be many failures, so we just rescan the the failures key for all tests which currently have a failure, and send the diff (tests which used to have a failure and now don't) to the dashboard.
=> Properly send failure deletion events

src/hypofuzz/corpus.py, src/hypofuzz/database.py, src/hypofuzz/entrypoint.py
This fixes a keyerror bug on master, where we tried to `self.corpus.remove(choices)` when the choice sequence wasn't actually in our corpus, because two fingerprints F1 and F2 both had the same choice sequence `choices`, and F1 evicted the choices from the corpus first (no error), followed by F2 later (which errored). Now we only evict when a choice sequence has no corresponding fingerprints.
=> Fix corpus eviction under instability

src/hypofuzz/collection.py, src/hypofuzz/dashboard/dashboard.py, src/hypofuzz/dashboard/patching.py, src/hypofuzz/hypofuzz.py, src/hypofuzz/provider.py, tests/test_collection.py, tests/test_corpus.py, tests/test_coverage.py, tests/test_database.py, tests/test_fuzz_process.py
in preparation for a `FuzzWorker` which manages multiple targets; I want to avoid the connotation of "fuzzprocess" <-> "cpu core"
=> Rename FuzzProcess to FuzzTarget

deps/check.txt, deps/docs.txt, deps/test-old.txt, deps/test.txt, src/hypofuzz/bayes.py, src/hypofuzz/hypofuzz.py, tests/test_bayes.py
I don't want to go all the way to thompson sampling yet, but softmax should be better than the current epsilon-greedy, especially when our estimators are as unstable as they are
Also improves our estimator to "behaviors per second" instead of "behaviors per input", and batches targets by 100 inputs instead of 1
=> Use softmax for multi-armed bandit

src/hypofuzz/frontend/src/components/CoverageGraph.tsx, src/hypofuzz/frontend/src/styles/styles.scss
Unfortunately `translate(90)` for the y axis makes the text and svg a bit blurry. Apparently this is a known issue: https://stackoverflow.com/questions/20326220/blurry-text-on-transformrotate-in-chrome. I've hacked around it for the text, but the icon is still blurry (on chrome + macos, anyway).
=> Refactor coverage graph to move axes out of svg

src/hypofuzz/collection.py, src/hypofuzz/detection.py, src/hypofuzz/hypofuzz.py, tests/common.py, tests/test_fixtures.py, tests/test_fuzzing.py, tests/test_unittest.py
Turns out this wasn't too hard to support, at least for simple usages.
docs update coming soon; preview:
```
Pytest and Unittest compatibility
---------------------------------
HypoFuzz is compatible with almost all features of Pytest and Unittest. The features which are not are listed below. If any of these features are important to you, please `get in touch <mailto:sales@hypofuzz.com?subject=Test%20runner%20feature%20support>`__! They are not yet implemented in HypoFuzz due to low perceived use.
* Pytest's :ref:`xunit-style setup methods <pytest:xunitsetup>` setup and teardown methods. Like Pytest, we recommend using fixtures instead.
* ``setup_module``, ``teardown_module``
* ``setup_class``, ``teardown_class``
* ``setup_method``, ``teardown_method``
* ``setup_function``, …
```
=> Add support for unittest and class-based pytest

deps/check.txt, deps/docs.txt, deps/test.txt, src/hypofuzz/frontend/src/pages/Workers.tsx, src/hypofuzz/frontend/src/styles/styles.scss, src/hypofuzz/frontend/src/tyche/Features.tsx, src/hypofuzz/frontend/src/tyche/FilterContext.tsx, src/hypofuzz/frontend/src/tyche/Filters.tsx, src/hypofuzz/frontend/src/tyche/MosaicChart.tsx, src/hypofuzz/frontend/src/tyche/NominalChart.tsx, src/hypofuzz/frontend/src/tyche/Tyche.tsx, src/hypofuzz/hypofuzz.py
Stability is a new tyche feature:
The gear icon indicates we generate this automatically, to avoid confusing the user ("why do I have a feature which doesn't correspond to any event/target/note call in my code?") 
I do not know why there are so many "unknown" stability events here. There should be 0. Probably a bug.
=> Save reports on worker switch + Tyche improvements

src/hypofuzz/dashboard/test.py, src/hypofuzz/frontend/src/components/graph/CoverageGraph.tsx, src/hypofuzz/frontend/src/components/graph/DataLines.tsx, src/hypofuzz/frontend/src/components/graph/types.ts, src/hypofuzz/provider.py
Lines show as hovered within a 10px radius now, instead of only directly on hover. The implementation is more complicated than it sounds: we build a quadtree of sampled points from the lines, for efficient range checking, to avoid O(n) sqrts every iteration.
=> Better graph hover and stability computation

src/hypofuzz/database/database.py, src/hypofuzz/hypofuzz.py, src/hypofuzz/provider.py, src/hypofuzz/utils.py, tests/test_database.py, tests/test_workers.py
We were associating `WorkerIdentity` with the database key of a `FuzzTarget` before. But a worker might have many targets. This pulls out the database entry to a top-level key. 
One effect of this is `worker_identity(in_directory=...)` for the git hash search is no longer unambiguous in which directory we should choose, since a worker has multiple collected targets. Currently we pick an arbitrary one, but we might do something smarted in the future (smallest parent shared by all targets? careful of outliers...). This only causes problems with submodules/etc, so I'm not too worried.
=> Refactor worker identity

src/hypofuzz/dashboard/api.py, src/hypofuzz/dashboard/models.py, src/hypofuzz/dashboard/websocket.py, src/hypofuzz/database/models.py, src/hypofuzz/frontend/src/components/TestTable.tsx, src/hypofuzz/frontend/src/context/DataProvider.tsx, src/hypofuzz/frontend/src/pages/CollectionStatus.tsx, src/hypofuzz/frontend/src/utils/fuzzjson.ts, src/hypofuzz/frontend/src/utils/utils.ts, src/hypofuzz/frontend/tests/utils.test.ts, src/hypofuzz/hypofuzz.py, src/hypofuzz/utils.py
fuzzjson inf/nan values are now stored at the observation/database/model level, since iterating over all observations when serializing gets expensive quickly.
=> Remove common nodeid prefix in display, fuzzjson performance improvements

src/hypofuzz/dashboard/patching.py, src/hypofuzz/frontend/src/tyche/Representation.tsx, src/hypofuzz/frontend/src/tyche/Summary.tsx, src/hypofuzz/frontend/src/tyche/Tyche.tsx, src/hypofuzz/frontend/src/utils/tooltip.tsx
We were only computing the patch of the last example before, due to a mismatch of what the `hypothesis.patching` api wants. Also improves memory usage by holding the right representation in memory instead of a bunch of duplicated `(before, after)` tuples.
=> Fix and improve patch computation
