Zac-HD/hypofuzz

.github/workflows/ci.yml
deps/check.txt
deps/docs.txt
deps/test-old.txt
deps/test.in
deps/test.txt
docs-src/changelog.md
setup.py
src/hypofuzz/__init__.py
src/hypofuzz/corpus.py
src/hypofuzz/hy.py
src/hypofuzz/interface.py
tests/test_corpus.py
tests/test_e2e.py

Fixes #35, after considerably more delay than ideal.  
(alas, I only have so much free time, and Hypothesis and CPython both come first 😞)

Update for new Pytest and Hypothesis versions

---

.github/workflows/ci.yml

let's give this a shot for the new pyproject.toml

Try fix ci build

---

pyproject.toml
src/hypofuzz/build.py

Tested to work locally, let's see if CI is happy.

Fix CI build

---

docs-src/changelog.md
src/hypofuzz/__init__.py
src/hypofuzz/build.py

I had this right the first time!

Build before release

---

.github/workflows/ci.yml
docs-src/changelog.md
src/hypofuzz/__init__.py
src/hypofuzz/frontend/package-lock.json
src/hypofuzz/frontend/package.json
src/hypofuzz/frontend/src/App.tsx
src/hypofuzz/frontend/src/components/CoverageGraph.tsx
src/hypofuzz/frontend/src/components/CoveringExamples.tsx
src/hypofuzz/frontend/src/components/Layout.tsx
src/hypofuzz/frontend/src/components/TestTable.tsx
src/hypofuzz/frontend/src/components/Toggle.tsx
src/hypofuzz/frontend/src/context/WebSocketContext.tsx
src/hypofuzz/frontend/src/hooks/usePreference.ts
src/hypofuzz/frontend/src/main.tsx
src/hypofuzz/frontend/src/pages/Patches.tsx
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/pages/Tests.tsx
src/hypofuzz/frontend/src/styles.scss
src/hypofuzz/frontend/src/types/dashboard.ts
src/hypofuzz/frontend/src/utils/testStats.ts

Run prettier and add CI check

---

docs-src/changelog.md
src/hypofuzz/__init__.py
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/components/TestTable.tsx
src/hypofuzz/frontend/src/context/WebSocketContext.tsx
src/hypofuzz/frontend/src/pages/CollectionStatus.tsx
src/hypofuzz/frontend/src/styles.scss
src/hypofuzz/frontend/src/types/dashboard.ts
src/hypofuzz/frontend/src/utils/testStats.ts

Add ability to sort tables 

---

.github/workflows/ci.yml

try remove trailing slash

---

.github/workflows/ci.yml
docs-src/changelog.md
src/hypofuzz/__init__.py
src/hypofuzz/frontend/package-lock.json
src/hypofuzz/frontend/package.json
src/hypofuzz/frontend/src/components/CoveringExamples.tsx
src/hypofuzz/frontend/src/components/Layout.tsx
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/components/TestTable.tsx
src/hypofuzz/frontend/src/pages/CollectionStatus.tsx
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/styles.scss

Closes #67
I'm not particularly happy with the placement of the search box, but I don't have any better ideas!

Add ability to filter table rows

---

.github/workflows/ci.yml
docs-src/changelog.md
src/hypofuzz/__init__.py
src/hypofuzz/frontend/src/components/StatusPill.tsx
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/components/TestTable.tsx
src/hypofuzz/frontend/src/components/Tooltip.tsx
src/hypofuzz/frontend/src/pages/CollectionStatus.tsx
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/styles.scss
src/hypofuzz/frontend/src/utils/testStats.ts

\+ minor ui improvements to the individual test page.

Use icons for test table

---

.github/workflows/ci.yml

I can't explain why this would change anything, but it's the only thing I modified in `_static`

Load-bearing doctree..?

---

.github/workflows/ci.yml
docs-src/changelog.md
src/hypofuzz/__init__.py
src/hypofuzz/dashboard.py
src/hypofuzz/frontend/src/components/CoverageGraph.tsx
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/components/TestTable.tsx
src/hypofuzz/frontend/src/pages/Tests.tsx
src/hypofuzz/frontend/src/styles.scss
src/hypofuzz/interface.py
tests/common.py
tests/test_database.py

We weren't doing this before, either because the manual invocation of pytest doesn't run other plugins, or because the hypothesis plugin adds the key at `pytest_runtest_call` and not at collection time.

Include parametrization in db key

---

src/hypofuzz/frontend/package-lock.json
src/hypofuzz/frontend/package.json
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/pages/CollectionStatus.tsx
src/hypofuzz/frontend/src/pages/Patches.tsx
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/styles.scss
src/hypofuzz/frontend/src/utils/prototypes.tsx

Using https://prismjs.com/ for syntax highlighting, currently only for failures:
I went with prism over https://highlightjs.org/ since prism claims to be a much smaller bundle size, which seems to check out, though I didn't actually test highlight js.

Various improvements

---

.github/workflows/ci.yml

Trying to get this working independently of #91

Try lfs docs build

---

src/hypofuzz/__init__.py
src/hypofuzz/docs/changelog.md
tests/common.py
tests/test_e2e.py

Let's run a manual test to make sure the docs bundling works with pypi pushes

Bump version

---

src/hypofuzz/corpus.py
src/hypofuzz/hypofuzz.py
src/hypofuzz/mutator.py
src/hypofuzz/utils.py

some uncontroversial changes to make the diff in https://github.com/Zac-HD/hypofuzz/pull/113 more palatable

Move a few things

---

build.sh
src/hypofuzz/dashboard.py
src/hypofuzz/docs/manual/database.rst
src/hypofuzz/frontend/src/components/CoverageGraph.tsx
src/hypofuzz/frontend/src/components/Pagination.tsx
src/hypofuzz/frontend/src/styles.scss
src/hypofuzz/frontend/src/tyche/Features.tsx
src/hypofuzz/frontend/src/tyche/NominalChart.tsx
src/hypofuzz/frontend/src/tyche/Representation.tsx

I ran `hypothesis fuzz` overnight and then ran the dashboard under pyinstrument, and found some easy wins.

Performance + Tyche UI improvements

---

src/hypofuzz/frontend/src/components/CoverageGraph.tsx
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/components/Toggle.tsx
src/hypofuzz/frontend/src/hooks/useIsMobile.ts
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/styles.scss
src/hypofuzz/frontend/src/tyche/MosaicChart.tsx
src/hypofuzz/frontend/src/tyche/Tyche.tsx

(@Zac-HD this switches to icons for graph toggles on mobile. The tyche layout changes I would classify as "bugfix"; more to come there)

UI improvements

---

src/hypofuzz/frontend/src/components/CoverageGraph.tsx
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/context/DataProvider.tsx
src/hypofuzz/frontend/src/tyche/NominalChart.tsx
src/hypofuzz/frontend/src/tyche/Samples.tsx
src/hypofuzz/frontend/src/types/dashboard.ts
src/hypofuzz/frontend/src/utils/utils.tsx
src/hypofuzz/frontend/tsconfig.json

Tyche change: don't count a minimum of one unique repr per repr (so a set of reprs which are all the same are now counted as n duplicates, not 1 unique and n - 1 duplicates. I think this is more intuitive)

UI cleanups

---

src/hypofuzz/frontend/eslint.config.mjs
src/hypofuzz/frontend/package-lock.json
src/hypofuzz/frontend/package.json
src/hypofuzz/frontend/src/App.tsx
src/hypofuzz/frontend/src/components/Collapsible.tsx
src/hypofuzz/frontend/src/components/CoverageGraph.tsx
src/hypofuzz/frontend/src/components/Layout.tsx
src/hypofuzz/frontend/src/components/Pagination.tsx
src/hypofuzz/frontend/src/components/Table.tsx
src/hypofuzz/frontend/src/components/TestTable.tsx
src/hypofuzz/frontend/src/context/DataProvider.tsx
src/hypofuzz/frontend/src/hooks/useIsMobile.ts
src/hypofuzz/frontend/src/hooks/useSetting.ts
src/hypofuzz/frontend/src/main.tsx
src/hypofuzz/frontend/src/pages/CollectionStatus.tsx
src/hypofuzz/frontend/src/pages/Patches.tsx
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/pages/Tests.tsx
src/hypofuzz/frontend/src/tyche/FilterContext.tsx
src/hypofuzz/frontend/src/tyche/Filters.tsx
src/hypofuzz/frontend/src/tyche/MosaicChart.tsx
src/hypofuzz/frontend/src/tyche/NominalChart.tsx
src/hypofuzz/frontend/src/tyche/Representation.tsx
src/hypofuzz/frontend/src/tyche/Tyche.tsx
src/hypofuzz/frontend/src/tyche/TycheSection.tsx
src/hypofuzz/frontend/src/utils/api.ts
src/hypofuzz/frontend/vite.config.ts

only using eslint for import sorting at the moment

Install eslint, chunk build output

---

src/hypofuzz/dashboard/dashboard.py
src/hypofuzz/dashboard/models.py
src/hypofuzz/frontend/src/App.tsx
src/hypofuzz/frontend/src/components/Notification.tsx
src/hypofuzz/frontend/src/components/ProgressBar.tsx
src/hypofuzz/frontend/src/context/DataProvider.tsx
src/hypofuzz/frontend/src/context/NotificationProvider.tsx
src/hypofuzz/frontend/src/styles.scss

Disappears on click, updates automatically as tests load in the background. Only shows when not all tests are loaded from db yet
Preview:

Show notification when dashboard is still starting up

---

.github/workflows/ci.yml
build.sh
scripts/release.py
src/hypofuzz/docs/_static/no-scroll.css
src/hypofuzz/docs/changelog.md
src/hypofuzz/docs/conf.py

Adds a mostly untested CI workflow for publishing github releases for the next time we do a release.

Docs improvements + github release script

---

src/hypofuzz/provider.py
tests/test_corpus.py
tests/test_provider.py

some refactor comments from https://github.com/Zac-HD/hypofuzz/pull/177

Refactor to use a single queue

---

src/hypofuzz/provider.py
tests/common.py
tests/test_fuzzing.py

https://github.com/Zac-HD/hypofuzz/pull/193#discussion_r2211837821
I think it's still reasonable to bucket here, I'm not against mixing in "largest-yet-seen" as well though for more granularity

Fix and test `target` bucketing code

---

src/hypofuzz/frontend/index.html
src/hypofuzz/frontend/src/Layout.tsx
src/hypofuzz/frontend/src/hooks/useSetting.ts
src/hypofuzz/frontend/src/pages/Patches.tsx
src/hypofuzz/frontend/src/styles/styles.scss
src/hypofuzz/frontend/src/tyche/Representation.tsx
src/hypofuzz/frontend/src/tyche/Samples.tsx

I'm surprised every time by how big of a difference adding icons makes. I don't dislike the diff or collection icons, but we might be able to do better.

Styling and slight wording change

---

src/hypofuzz/frontend/src/components/graph/CoverageGraph.tsx
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/styles/styles.scss

Tweak "separate" worker view colors, add a legend

---

src/hypofuzz/database.py
src/hypofuzz/frontend/src/context/DataProvider.tsx
src/hypofuzz/frontend/src/pages/Test.tsx
tests/strategies.py
tests/test_database.py
tests/test_provider.py

Including a fix for a pretty bad copy-paste bug. I've added good test coverage so this doesn't happen again, and in the process found another bug with fully-shrunk events not being parsed correctly.

Fix a few database bugs + fix react rerendering

---

src/hypofuzz/frontend/src/components/graph/CoverageGraph.tsx
src/hypofuzz/frontend/src/components/graph/useZoom.ts
src/hypofuzz/frontend/src/pages/Test.tsx
src/hypofuzz/frontend/src/pages/Tests.tsx
src/hypofuzz/frontend/src/styles/styles.scss
src/hypofuzz/frontend/vite.config.ts

We were rebuilding the quadtree every zoom frame. oops.

Improve graph zoom performance
